database:
  default:
    type:  "mysql"
    # link:  "root:@tcp(127.0.0.1:3306)/zsxq"
    link:  "root:woaini520@tcp(mysql)/zsxq"

wechat:
    key:    "xxxxxxx-ce47-4aa7-9fa1-xxxxxx"

zsxq_access_token:
    token:    "xxxxxxx-752F-369F-1BC7-1287690C57B0_xxxxxxxxxxx"

zsxq_group:
  - id: "xxxxx"
  - id: "xxxxxxxx"